language: python
env:
  - PYTHON_VERSION=3.6 IPYTHON_KERNEL=python3
before_install:
  - wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes --quiet conda
install:
  - conda create -n testenv --yes -q -c conda-forge python=$PYTHON_VERSION pip numpy scipy matplotlib
  - source activate testenv
  - conda install --yes -q -c conda-forge scikit-learn scikit-image netcdf4 xarray numba
  - pip install pyyaml
  - pip install tensorflow>=2.0
  - pip install keras
  - pip install .
  - mkdir exp_travis
  - mkdir exp_travis/exp_poly
  - mkdir exp_travis/exp_gan
  - mkdir exp_travis/exp_ann
script:
  - python train_lorenz_gan.py config/lorenz_gan_travis.yaml -g
  - python run_lorenz_forecast.py config/forecast_poly_travis.yaml -p 1
  - python run_lorenz_forecast.py config/forecast_ann_travis.yaml -p 2
  - python run_lorenz_forecast.py config/forecast_gan_travis.yaml -p 1
notifications:
  email: true
