lorenz:
    K: 8
    J: 32
    h: 1
    b: 10.0
    c: 10.0
    F: 30.0
    time_step: 0.001
    num_steps: 1000000
    skip: 5
    burn_in: 2000
gan:
    structure: dense
    output: dist
    t_skip: 10
    x_skip: 1
    generator:
        num_cond_inputs: 3
        num_random_inputs: 2
        num_outputs: 1
        num_hidden: 3
        activation: tanh
    discriminator:
        num_cond_inputs: 3
        num_sample_inputs: 1
        num_hidden: 3
        activation: tanh
    gan_path: ./exp_mean
    batch_size: 128
    gan_index: 0
    num_epochs: [1, 5, 10]
    loss: "binary_crossentropy"
    metrics: ["accuracy"]
output_nc_file: ./exp_mean/lorenz_output.nc
output_csv_file: ./exp_mean/lorenz_combined_output.csv
