num_members: 1
initial_x: []
F: 20
u_model_name: gan
u_model_path: /glade/p/work/dgagne/exp_20_noise/gan_generator_0100_epoch_0040.h5
random_updater_path: /glade/p/work/dgagne/exp_20_noise/ar1_random_updater.pkl
num_steps: 2000000
num_random: 1
time_step: 0.005
random_seeds: [5000, 5500]
initial_step: 2000000
x_only: 0
predict_residuals: 0
lorenz_nc_file: /glade/p/work/dgagne/exp_20_noise/lorenz_output.nc
out_path: /glade/p/work/dgagne/exp_20_noise/gan_100_climate/
num_tf_threads: 8
