num_members: 5
initial_x: []
F: 30
u_model_name: gan
u_model_path: ./exp_u/gan_generator_0000_epoch_0010.h5
random_updater_path: ./exp_u/ar1_random_updater.pkl
num_steps: 200000
num_random: 8
time_step: 0.005
random_seeds: [5000, 6000]
initial_step: 1000000
x_only: False
lorenz_nc_file: ./exp_u/lorenz_output.nc
out_path: ./exp_climate/