num_members: 1
initial_x: []
F: 20
u_model_name: gan
u_model_path: /glade2/work/dgagne/exp_20_stoch/gan_generator_0000_epoch_0030.h5
random_updater_path: /glade2/work/dgagne/exp_20_stoch/ar1_random_updater.pkl
num_steps: 2000000
num_random: 1
time_step: 0.005
random_seeds: [5000, 5500]
initial_step: 2000000
x_only: 0
predict_residuals: 0
lorenz_nc_file: /glade2/work/dgagne/exp_20_stoch/lorenz_output.nc
out_path: /glade2/work/dgagne/exp_20_stoch/gan_000_climate/
num_tf_threads: 8
