num_members: 1
initial_x: []
F: 30
u_model_name: poly
u_model_path: /glade/scratch/dgagne/exp_u/u_poly_multi.pkl
random_updater_path: /glade/scratch/dgagne/exp_u/ar1_random_updater.pkl
num_steps: 2000000
num_random: 1
time_step: 0.005
random_seeds: [5000, 5500]
initial_step: 2000000
x_only: 1
call_param_once: 1
lorenz_nc_file: /glade/scratch/dgagne/exp_u/lorenz_output.nc
out_path: /glade/scratch/dgagne/exp_u/poly_multi_climate/
