num_members: 3
initial_x: []
F: 30
u_model_name: poly
u_model_path: ./exp_u/u_poly.pkl
random_updater_path: ./exp_u/ar1_random_updater.pkl
num_steps: 60000
num_random: 1
time_step: 0.005
random_seeds: [5000, 6000]
initial_step: 1000000
x_only: 1
lorenz_nc_file: ./exp_u/lorenz_output.nc
out_path: ./exp_climate_poly/