num_members: 5
initial_x: []
F: 30
u_model_name: gan
u_model_path: /glade/p/work/dgagne/exp_u/gan_generator_0000_epoch_0010.h5
random_updater_path: /glade/p/work/dgagne/exp_u/ar1_random_updater.pkl
num_steps: 3600000
num_random: 8
time_step: 0.005
random_seeds: [5000, 5500]
initial_step: 2000000
x_only: 0
lorenz_nc_file: /glade/p/work/dgagne/exp_u/lorenz_output.nc
out_path: /glade/p/work/dgagne/exp_u/gan_climate/