num_members: 3
initial_x: []
F: 15
u_model_name: gan
u_model_path: ./exp_pierre/gan_generator_0000_epoch_0030.h5
random_updater_path: ./exp_pierre/ar1_random_updater.pkl
num_steps: 10000
num_random: 34
time_step: 0.005
x_time_lag: 0
random_seeds: [5000, 6000]
initial_step: 600000
x_only: 1
call_param_once: 1
predict_residuals: 0
lorenz_nc_file: ./exp_pierre/lorenz_output.nc
out_path: ./exp_pierre/exp_gan/
num_tf_threads: 1
