num_members: 3
initial_x: []
F: 20
u_model_name: ann_res
u_model_path: ./exp_travis/annres_config_0040_opts.yaml
random_updater_path: ./exp_travis/ar1_random_updater.pkl
num_steps: 1000
num_random: 1
time_step: 0.005
x_time_lag: 0
random_seeds: [5000, 6000]
initial_step: 50000
x_only: 1
call_param_once: 1
predict_residuals: 1
lorenz_nc_file: ./exp_travis/lorenz_output.nc
out_path: ./exp_travis/exp_ann/