num_members: 50
initial_x: []
F: 30
u_model_name: poly
u_model_path: /glade/p/work/dgagne/exp_u/u_poly.pkl
random_updater_path: /glade/p/work/dgagne/exp_u/ar1_random_updater.pkl
num_steps: 400
num_random: 1
time_step: 0.005
x_time_lag: 0
random_seeds: [5000, 15000]
initial_step: [3000000, 18000000, 20000]
x_only: 1
call_param_once: True
lorenz_nc_file: /glade/p/work/dgagne/exp_u/lorenz_output.nc
out_path: /glade/scratch/dgagne/exp_u/poly_weather/

