num_members: 50
initial_x: []
F: 30
u_model_name: gan
u_model_path: /glade/p/work/dgagne/exp_u/gan_generator_0000_epoch_0010.h5
random_updater_path: /glade/p/work/dgagne/exp_u/ar1_random_updater.pkl
num_steps: 400
num_random: 8
time_step: 0.005
random_seeds: [5000, 15000]
initial_step: [3000000, 18000000, 5000]
x_only: False
call_param_once: True
lorenz_nc_file: /glade/p/work/dgagne/exp_u/lorenz_output.nc
out_path: /glade/p/work/dgagne/exp_u/gan_weather/