num_members: 40
initial_x: []
F: 20
u_model_name: poly
u_model_path: /glade/p/work/dgagne/exp_20_noise/u_poly_add.pkl
random_updater_path: /glade/p/work/dgagne/exp_20_noise/ar1_random_updater.pkl
num_steps: 400
num_random: 1
time_step: 0.005
x_time_lag: 0
random_seeds: [5000, 15000]
initial_step: [3000000, 18000000, 20000]
x_only: 1
call_param_once: 1
predict_residuals: 1
lorenz_nc_file: /glade/p/work/dgagne/exp_20_noise/lorenz_output.nc
out_path: /glade/p/work/dgagne/exp_20_noise/poly_add_weather/

