num_members: 10
initial_x: []
F: 30
u_model_name: gan
u_model_path: ./exp_u/gan_generator_0000_epoch_0010.h5
random_updater_path: ./exp_u/ar1_random_updater.pkl
num_steps: 400
num_random: 8
time_step: 0.005
random_seeds: [5000, 6000]
initial_step: [1100000, 1500000, 100000]
x_only: 0
call_param_once: 1
lorenz_nc_file: ./exp_u/lorenz_output.nc
out_path: ./exp_u/
