lorenz:
    K: 8
    J: 32
    h: 1
    b: 10.0
    c: 10.0
    F: 30.0
    time_step: 0.001
    num_steps: 1000000
    skip: 5
    burn_in: 2000
gan:
    structure: dense
    t_skip: 10
    x_skip: 1
    output: sample
    generator:
        num_cond_inputs: 1
        num_random_inputs: 5
        num_outputs: 32
        num_hidden: 16
        activation: selu
        dropout_alpha: 0.5
    discriminator:
        num_cond_inputs: 1
        num_sample_inputs: 32
        num_hidden: 16
        activation: selu
    gan_path: ./exp_dense/
    batch_size: 128
    gan_index: 0
    num_epochs: [1, 5, 10]
    loss: "mse"
    metrics: ["accuracy"]
random_updater:
    out_file: ./exp_dense/ar1_random_updater.pkl
histogram:
    num_x_bins: 30
    num_u_bins: 30
    out_file: ./exp_dense/u_histogram.pkl
output_nc_file: ./exp_dense/lorenz_output.nc
output_csv_file: ./exp_dense/lorenz_combined_output.csv
