lorenz:
    K: 8
    J: 32
    h: 1
    b: 10.0
    c: 10.0
    F: 30.0
    time_step: 0.001
    num_steps: 1000000
    skip: 5
    burn_in: 2000
gan:
    structure: conv
    t_skip: 10
    x_skip: 1
    output: sample
    generator:
        num_cond_inputs: 1
        num_random_inputs: 1
        num_outputs: 32
        activation: selu
        min_conv_filters: 8
        min_data_width: 4
        filter_width: 5
        dropout_alpha: 0.2
    discriminator:
        num_cond_inputs: 1
        num_sample_inputs: 32
        activation: selu
        min_conv_filters: 8
        min_data_width: 4
        filter_width: 5
        dropout_alpha: 0.1
    gan_path: ./exp
    batch_size: 128
    gan_index: 0
    loss: binary_crossentropy
    learning_rate: 0.0005
    num_epochs: [1, 2, 3, 4, 5, 8, 10]
    metrics: ["accuracy"]
random_updater:
    out_file: ./exp/ar1_random_updater.pkl
histogram:
    num_x_bins: 30
    num_u_bins: 30
    out_file: ./exp/u_histogram.pkl
output_nc_file: ./exp/lorenz_output.nc
output_csv_file: ./exp/lorenz_combined_output.csv
