num_members: 40
initial_x: []
F: 20
u_model_name: gan
u_model_path: /glade/work/dgagne/exp_20_stoch/gan_generator_0202_epoch_0030.h5
random_updater_path: /glade/work/dgagne/exp_20_stoch/offline/ar1/ar1_random_updater_0202.pkl
num_steps: 400
num_random: 1
time_step: 0.005
x_time_lag: 0
random_seeds: [5000, 15000]
initial_step: [3000000, 18000000, 20000]
x_only: 1
call_param_once: 1
predict_residuals: 0
max_tasks: 1000
lorenz_nc_file: /glade/work/dgagne/exp_20_stoch/lorenz_output.nc
out_path: /glade/work/dgagne/exp_20_stoch/v2/gan_202_weather/

