data_file: "/glade/work/dgagne/exp_20_stoch/lorenz_combined_output_test_x0.csv"
gan_path: "/glade/work/dgagne/exp_20_stoch/"
gan_indices: [500, 501, 502, 503, 602, 603, 702]
out_path: "/glade/work/dgagne/exp_20_stoch/offline_20190313/"
seed: 23904
batch_size: 262144
meta_columns: ["x_index", "time", "step"]

